### ISSUE TITLE
Contact Link

### ISSUE THREAD

**Issue by erloo** [PowerDocs-net/platform_feedback#1] opened 2022-05-08 20:00 UTC
**Describe the bug**
When you want to go to the "Feedback" page in the footer, it redirects to a non-existing page, "404 | This page could not be found."

**To Reproduce**
1. Go to https://powerdocs.net/ the homepage
2. Click on Feedback in the footer
3. See error

**Expected behavior**
You should get to the Feedback page.

**Screenshots**
![image](https://user-images.githubusercontent.com/78352692/167313613-4a09b58a-1200-445f-86e9-1905aeeebb05.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 101.0.4951.54 (Offizieller Build) (64-Bit)

**Comment by SneakyMammut** [comment] 2022-05-09 15:19
Thanks a lot. The issue is now resolved in the current build.

**Closed as completed by SneakyMammut** 2022-05-09 15:19 UTC
Labels: bug
